using System.Collections.Generic;
using System.Globalization;

namespace YouTube4KDownloader;

public static class LocalizationManager
{
    private static readonly Dictionary<string, Dictionary<string, string>> D = new()
    {
        ["ko"] = new()
        {
            ["WindowTitle"] = "4K 영상 다운로더",
            ["AppTitle"] = "4K 영상 다운로더",
            ["CopyrightNotice"] = "본인이 소유하거나 다운로드 허가를 받은 영상에만 사용하세요.",
            ["Language"] = "언어",
            ["AutoLanguage"] = "자동(Windows 언어)",
            ["DownloadTab"] = "다운로드",
            ["HistoryTab"] = "기록",
            ["VideoUrl"] = "영상 URL",
            ["UrlInputHint"] = "여러 링크를 줄바꿈 또는 공백으로 구분해 입력할 수 있습니다.",
            ["Paste"] = "붙여넣기",
            ["AddQueue"] = "여러 개 대기열 추가",
            ["Inspect"] = "정보 확인",
            ["AutoClipboard"] = "복사한 YouTube 링크 자동 붙여넣기",
            ["AutoQueueClipboard"] = "복사한 링크 자동 대기열 추가",
            ["AutoStartAfterAdd"] = "URL 추가 후 자동 다운로드 시작",
            ["ClipboardQueued"] = "클립보드 링크 {0}개를 대기열에 자동 추가했습니다.",
            ["ClipboardPasted"] = "클립보드에서 {0}개 링크를 자동으로 붙여넣었습니다.",
            ["UrlsAdded"] = "{0}개 링크를 대기열에 추가했습니다.",
            ["DuplicateUrls"] = "이미 대기열에 등록된 링크입니다.",
            ["InfoPlaceholder"] = "영상 정보를 확인하면 제목이 표시됩니다.",
            ["SaveFolder"] = "저장 폴더",
            ["Browse"] = "찾아보기",
            ["Quality"] = "화질",
            ["OutputFormat"] = "출력 형식",
            ["Best4K"] = "최고 화질 (최대 4K)",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "재생목록 전체",
            ["Subtitles"] = "자막",
            ["AutoSubtitles"] = "자동 자막",
            ["Thumbnail"] = "썸네일 저장",
            ["Metadata"] = "메타데이터 삽입",
            ["OpenAfter"] = "완료 후 폴더 열기",
            ["FileName"] = "파일명 형식",
            ["BrowserCookies"] = "브라우저 로그인",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "다운로드 큐",
            ["Log"] = "로그",
            ["StartQueue"] = "큐 다운로드 시작",
            ["Remove"] = "선택 제거",
            ["Clear"] = "전체 지우기",
            ["Cancel"] = "취소",
            ["Title"] = "제목",
            ["Status"] = "상태",
            ["Progress"] = "진행률",
            ["Date"] = "날짜",
            ["Format"] = "형식",
            ["Success"] = "성공",
            ["Redownload"] = "다시 다운로드",
            ["ClearHistory"] = "기록 지우기",
            ["OpenFolder"] = "폴더 열기",
            ["UpdateTools"] = "도구 업데이트",
            ["ClearLog"] = "로그 지우기",
            ["Waiting"] = "대기",
            ["Failed"] = "실패",
            ["Ready"] = "준비됨",
            ["CheckingInfo"] = "정보 확인 중...",
            ["InfoCancelled"] = "정보 확인이 취소되었습니다.",
            ["NoTitle"] = "제목 없음",
            ["Unknown"] = "알 수 없음",
            ["Channel"] = "채널",
            ["Duration"] = "길이",
            ["PreparingDownload"] = "다운로드 준비 중...",
            ["DownloadInProgress"] = "다운로드 중",
            ["RemainingTime"] = "남은 시간",
            ["Completed"] = "완료",
            ["Cancelled"] = "취소됨",
            ["QueueComplete"] = "다운로드 큐 처리가 완료되었습니다.",
            ["DownloadCompleteTitle"] = "다운로드 완료",
            ["QueueCompleteNotification"] = "다운로드가 완료되었습니다. 성공 {0}개, 실패 {1}개",
            ["NotificationFailed"] = "Windows 완료 알림을 표시하지 못했습니다.",
            ["UserCancelled"] = "사용자가 다운로드를 취소했습니다.",
            ["UpdatingTools"] = "도구 업데이트 중...",
            ["ToolsUpdated"] = "yt-dlp와 FFmpeg 업데이트가 완료되었습니다.",
            ["InvalidUrl"] = "올바른 영상 URL을 입력해 주세요.",
            ["UrlCheck"] = "URL 확인",
            ["ErrorOccurred"] = "오류 발생",
            ["ErrorPrefix"] = "오류",
            ["ErrorHelp"] = "로그를 확인하고 필요하면 도구 업데이트를 실행해 주세요.",
            ["Cancelling"] = "취소 중...",
            ["FolderDialogTitle"] = "저장 폴더 선택",
            ["CookiesDialogTitle"] = "cookies.txt 선택",
            ["CookiesFilter"] = "Cookies 파일 (*.txt)|*.txt|모든 파일 (*.*)|*.*",
            ["ToolsReady"] = "필수 도구 준비 완료",
            ["DownloadingYtDlp"] = "yt-dlp 다운로드 중...",
            ["DownloadingFfmpeg"] = "FFmpeg 다운로드 중...",
            ["PremiereEncoding"] = "Premiere Pro 호환 H.264/AAC 인코딩 중... ({0}/{1})",
            ["PremiereEncodingDone"] = "Premiere Pro 호환 파일 생성 완료: {0}",
            ["PremiereSourceNotFound"] = "다운로드된 영상 파일 경로를 확인하지 못했습니다.",
        },
        ["en"] = new()
        {
            ["WindowTitle"] = "4K Video Downloader",
            ["AppTitle"] = "4K Video Downloader",
            ["CopyrightNotice"] = "Use this only for videos you own or have permission to download.",
            ["Language"] = "Language",
            ["AutoLanguage"] = "Automatic (Windows language)",
            ["DownloadTab"] = "Download",
            ["HistoryTab"] = "History",
            ["VideoUrl"] = "Video URL",
            ["UrlInputHint"] = "Enter multiple links separated by spaces or new lines.",
            ["Paste"] = "Paste",
            ["AddQueue"] = "Add multiple to queue",
            ["Inspect"] = "Check info",
            ["AutoClipboard"] = "Automatically paste copied YouTube links",
            ["AutoQueueClipboard"] = "Automatically add copied links to queue",
            ["AutoStartAfterAdd"] = "Automatically start after adding URL",
            ["ClipboardQueued"] = "Automatically added {0} clipboard link(s) to the queue.",
            ["ClipboardPasted"] = "Automatically pasted {0} link(s) from the clipboard.",
            ["UrlsAdded"] = "Added {0} link(s) to the queue.",
            ["DuplicateUrls"] = "The links are already in the queue.",
            ["InfoPlaceholder"] = "Video title appears after checking information.",
            ["SaveFolder"] = "Save folder",
            ["Browse"] = "Browse",
            ["Quality"] = "Quality",
            ["OutputFormat"] = "Output format",
            ["Best4K"] = "Best quality (up to 4K)",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "Entire playlist",
            ["Subtitles"] = "Subtitles",
            ["AutoSubtitles"] = "Auto subtitles",
            ["Thumbnail"] = "Save thumbnail",
            ["Metadata"] = "Embed metadata",
            ["OpenAfter"] = "Open folder when complete",
            ["FileName"] = "Filename template",
            ["BrowserCookies"] = "Browser login",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "Download queue",
            ["Log"] = "Log",
            ["StartQueue"] = "Start queue",
            ["Remove"] = "Remove selected",
            ["Clear"] = "Clear all",
            ["Cancel"] = "Cancel",
            ["Title"] = "Title",
            ["Status"] = "Status",
            ["Progress"] = "Progress",
            ["Date"] = "Date",
            ["Format"] = "Format",
            ["Success"] = "Success",
            ["Redownload"] = "Download again",
            ["ClearHistory"] = "Clear history",
            ["OpenFolder"] = "Open folder",
            ["UpdateTools"] = "Update tools",
            ["ClearLog"] = "Clear log",
            ["Waiting"] = "Waiting",
            ["Failed"] = "Failed",
            ["Ready"] = "Ready",
            ["CheckingInfo"] = "Checking information...",
            ["InfoCancelled"] = "Information check cancelled.",
            ["NoTitle"] = "No title",
            ["Unknown"] = "Unknown",
            ["Channel"] = "Channel",
            ["Duration"] = "Duration",
            ["PreparingDownload"] = "Preparing download...",
            ["DownloadInProgress"] = "Downloading",
            ["RemainingTime"] = "Remaining",
            ["Completed"] = "Completed",
            ["Cancelled"] = "Cancelled",
            ["QueueComplete"] = "Download queue completed.",
            ["DownloadCompleteTitle"] = "Download complete",
            ["QueueCompleteNotification"] = "Downloads finished. Successful: {0}, Failed: {1}",
            ["NotificationFailed"] = "Could not display the Windows completion notification.",
            ["UserCancelled"] = "Download cancelled by user.",
            ["UpdatingTools"] = "Updating tools...",
            ["ToolsUpdated"] = "yt-dlp and FFmpeg updated.",
            ["InvalidUrl"] = "Enter a valid video URL.",
            ["UrlCheck"] = "URL check",
            ["ErrorOccurred"] = "An error occurred",
            ["ErrorPrefix"] = "Error",
            ["ErrorHelp"] = "Check the log and update tools if necessary.",
            ["Cancelling"] = "Cancelling...",
            ["FolderDialogTitle"] = "Select save folder",
            ["CookiesDialogTitle"] = "Select cookies.txt",
            ["CookiesFilter"] = "Cookies files (*.txt)|*.txt|All files (*.*)|*.*",
            ["ToolsReady"] = "Required tools are ready",
            ["DownloadingYtDlp"] = "Downloading yt-dlp...",
            ["DownloadingFfmpeg"] = "Downloading FFmpeg...",
            ["PremiereEncoding"] = "Encoding Premiere Pro compatible H.264/AAC... ({0}/{1})",
            ["PremiereEncodingDone"] = "Premiere Pro compatible file created: {0}",
            ["PremiereSourceNotFound"] = "Could not determine the downloaded video file path.",
        },
        ["ja"] = new()
        {
            ["WindowTitle"] = "4K動画ダウンローダー",
            ["AppTitle"] = "4K動画ダウンローダー",
            ["CopyrightNotice"] = "所有している動画、またはダウンロード許可を得た動画にのみ使用してください。",
            ["Language"] = "言語",
            ["AutoLanguage"] = "自動（Windowsの言語）",
            ["DownloadTab"] = "ダウンロード",
            ["HistoryTab"] = "履歴",
            ["VideoUrl"] = "動画URL",
            ["UrlInputHint"] = "複数のリンクを改行または空白で区切って入力できます。",
            ["Paste"] = "貼り付け",
            ["AddQueue"] = "複数をキューに追加",
            ["Inspect"] = "情報を確認",
            ["AutoClipboard"] = "コピーしたYouTubeリンクを自動貼り付け",
            ["AutoQueueClipboard"] = "コピーしたリンクを自動でキューに追加",
            ["AutoStartAfterAdd"] = "URL追加後に自動でダウンロード開始",
            ["ClipboardQueued"] = "クリップボードのリンク{0}件をキューに自動追加しました。",
            ["ClipboardPasted"] = "クリップボードから{0}件のリンクを自動貼り付けしました。",
            ["UrlsAdded"] = "{0}件のリンクをキューに追加しました。",
            ["DuplicateUrls"] = "リンクはすでにキューにあります。",
            ["InfoPlaceholder"] = "情報を確認すると動画タイトルが表示されます。",
            ["SaveFolder"] = "保存先フォルダー",
            ["Browse"] = "参照",
            ["Quality"] = "画質",
            ["OutputFormat"] = "出力形式",
            ["Best4K"] = "最高画質（最大4K）",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "再生リスト全体",
            ["Subtitles"] = "字幕",
            ["AutoSubtitles"] = "自動字幕",
            ["Thumbnail"] = "サムネイルを保存",
            ["Metadata"] = "メタデータを埋め込む",
            ["OpenAfter"] = "完了後にフォルダーを開く",
            ["FileName"] = "ファイル名テンプレート",
            ["BrowserCookies"] = "ブラウザーログイン",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "ダウンロードキュー",
            ["Log"] = "ログ",
            ["StartQueue"] = "キューを開始",
            ["Remove"] = "選択項目を削除",
            ["Clear"] = "すべてクリア",
            ["Cancel"] = "キャンセル",
            ["Title"] = "タイトル",
            ["Status"] = "状態",
            ["Progress"] = "進行状況",
            ["Date"] = "日付",
            ["Format"] = "形式",
            ["Success"] = "成功",
            ["Redownload"] = "再ダウンロード",
            ["ClearHistory"] = "履歴をクリア",
            ["OpenFolder"] = "フォルダーを開く",
            ["UpdateTools"] = "ツールを更新",
            ["ClearLog"] = "ログをクリア",
            ["Waiting"] = "待機中",
            ["Failed"] = "失敗",
            ["Ready"] = "準備完了",
            ["CheckingInfo"] = "情報を確認中...",
            ["InfoCancelled"] = "情報確認がキャンセルされました。",
            ["NoTitle"] = "タイトルなし",
            ["Unknown"] = "不明",
            ["Channel"] = "チャンネル",
            ["Duration"] = "長さ",
            ["PreparingDownload"] = "ダウンロードを準備中...",
            ["DownloadInProgress"] = "ダウンロード中",
            ["RemainingTime"] = "残り時間",
            ["Completed"] = "完了",
            ["Cancelled"] = "キャンセル済み",
            ["QueueComplete"] = "ダウンロードキューが完了しました。",
            ["DownloadCompleteTitle"] = "ダウンロード完了",
            ["QueueCompleteNotification"] = "ダウンロードが完了しました。成功: {0}、失敗: {1}",
            ["NotificationFailed"] = "Windowsの完了通知を表示できませんでした。",
            ["UserCancelled"] = "ユーザーがダウンロードをキャンセルしました。",
            ["UpdatingTools"] = "ツールを更新中...",
            ["ToolsUpdated"] = "yt-dlpとFFmpegを更新しました。",
            ["InvalidUrl"] = "有効な動画URLを入力してください。",
            ["UrlCheck"] = "URL確認",
            ["ErrorOccurred"] = "エラーが発生しました",
            ["ErrorPrefix"] = "エラー",
            ["ErrorHelp"] = "ログを確認し、必要に応じてツールを更新してください。",
            ["Cancelling"] = "キャンセル中...",
            ["FolderDialogTitle"] = "保存先フォルダーを選択",
            ["CookiesDialogTitle"] = "cookies.txtを選択",
            ["CookiesFilter"] = "Cookiesファイル (*.txt)|*.txt|すべてのファイル (*.*)|*.*",
            ["ToolsReady"] = "必要なツールの準備が完了しました",
            ["DownloadingYtDlp"] = "yt-dlpをダウンロード中...",
            ["DownloadingFfmpeg"] = "FFmpegをダウンロード中...",
        },
        ["zh-Hans"] = new()
        {
            ["WindowTitle"] = "4K 视频下载器",
            ["AppTitle"] = "4K 视频下载器",
            ["CopyrightNotice"] = "仅用于您拥有或已获准下载的视频。",
            ["Language"] = "语言",
            ["AutoLanguage"] = "自动（Windows 语言）",
            ["DownloadTab"] = "下载",
            ["HistoryTab"] = "历史记录",
            ["VideoUrl"] = "视频 URL",
            ["UrlInputHint"] = "可用换行或空格分隔输入多个链接。",
            ["Paste"] = "粘贴",
            ["AddQueue"] = "批量加入队列",
            ["Inspect"] = "检查信息",
            ["AutoClipboard"] = "自动粘贴复制的 YouTube 链接",
            ["AutoQueueClipboard"] = "自动将复制的链接加入队列",
            ["AutoStartAfterAdd"] = "添加 URL 后自动开始下载",
            ["ClipboardQueued"] = "已自动将剪贴板中的 {0} 个链接加入队列。",
            ["ClipboardPasted"] = "已从剪贴板自动粘贴 {0} 个链接。",
            ["UrlsAdded"] = "已将 {0} 个链接加入队列。",
            ["DuplicateUrls"] = "链接已在队列中。",
            ["InfoPlaceholder"] = "检查信息后将显示视频标题。",
            ["SaveFolder"] = "保存文件夹",
            ["Browse"] = "浏览",
            ["Quality"] = "画质",
            ["OutputFormat"] = "输出格式",
            ["Best4K"] = "最佳画质（最高 4K）",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "整个播放列表",
            ["Subtitles"] = "字幕",
            ["AutoSubtitles"] = "自动字幕",
            ["Thumbnail"] = "保存缩略图",
            ["Metadata"] = "嵌入元数据",
            ["OpenAfter"] = "完成后打开文件夹",
            ["FileName"] = "文件名模板",
            ["BrowserCookies"] = "浏览器登录",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "下载队列",
            ["Log"] = "日志",
            ["StartQueue"] = "开始队列",
            ["Remove"] = "移除所选",
            ["Clear"] = "全部清除",
            ["Cancel"] = "取消",
            ["Title"] = "标题",
            ["Status"] = "状态",
            ["Progress"] = "进度",
            ["Date"] = "日期",
            ["Format"] = "格式",
            ["Success"] = "成功",
            ["Redownload"] = "重新下载",
            ["ClearHistory"] = "清除历史记录",
            ["OpenFolder"] = "打开文件夹",
            ["UpdateTools"] = "更新工具",
            ["ClearLog"] = "清除日志",
            ["Waiting"] = "等待中",
            ["Failed"] = "失败",
            ["Ready"] = "就绪",
            ["CheckingInfo"] = "正在检查信息...",
            ["InfoCancelled"] = "信息检查已取消。",
            ["NoTitle"] = "无标题",
            ["Unknown"] = "未知",
            ["Channel"] = "频道",
            ["Duration"] = "时长",
            ["PreparingDownload"] = "正在准备下载...",
            ["DownloadInProgress"] = "正在下载",
            ["RemainingTime"] = "剩余时间",
            ["Completed"] = "已完成",
            ["Cancelled"] = "已取消",
            ["QueueComplete"] = "下载队列已完成。",
            ["DownloadCompleteTitle"] = "下载完成",
            ["QueueCompleteNotification"] = "下载完成。成功：{0}，失败：{1}",
            ["NotificationFailed"] = "无法显示 Windows 完成通知。",
            ["UserCancelled"] = "用户已取消下载。",
            ["UpdatingTools"] = "正在更新工具...",
            ["ToolsUpdated"] = "yt-dlp 和 FFmpeg 已更新。",
            ["InvalidUrl"] = "请输入有效的视频 URL。",
            ["UrlCheck"] = "URL 检查",
            ["ErrorOccurred"] = "发生错误",
            ["ErrorPrefix"] = "错误",
            ["ErrorHelp"] = "请检查日志，并在需要时更新工具。",
            ["Cancelling"] = "正在取消...",
            ["FolderDialogTitle"] = "选择保存文件夹",
            ["CookiesDialogTitle"] = "选择 cookies.txt",
            ["CookiesFilter"] = "Cookies 文件 (*.txt)|*.txt|所有文件 (*.*)|*.*",
            ["ToolsReady"] = "所需工具已就绪",
            ["DownloadingYtDlp"] = "正在下载 yt-dlp...",
            ["DownloadingFfmpeg"] = "正在下载 FFmpeg...",
        },
        ["zh-Hant"] = new()
        {
            ["WindowTitle"] = "4K 影片下載器",
            ["AppTitle"] = "4K 影片下載器",
            ["CopyrightNotice"] = "僅用於您擁有或已獲准下載的影片。",
            ["Language"] = "語言",
            ["AutoLanguage"] = "自動（Windows 語言）",
            ["DownloadTab"] = "下載",
            ["HistoryTab"] = "歷史記錄",
            ["VideoUrl"] = "影片 URL",
            ["UrlInputHint"] = "可使用換行或空格分隔輸入多個連結。",
            ["Paste"] = "貼上",
            ["AddQueue"] = "批次加入佇列",
            ["Inspect"] = "檢查資訊",
            ["AutoClipboard"] = "自動貼上複製的 YouTube 連結",
            ["AutoQueueClipboard"] = "自動將複製的連結加入佇列",
            ["AutoStartAfterAdd"] = "新增 URL 後自動開始下載",
            ["ClipboardQueued"] = "已自動將剪貼簿中的 {0} 個連結加入佇列。",
            ["ClipboardPasted"] = "已從剪貼簿自動貼上 {0} 個連結。",
            ["UrlsAdded"] = "已將 {0} 個連結加入佇列。",
            ["DuplicateUrls"] = "連結已在佇列中。",
            ["InfoPlaceholder"] = "檢查資訊後將顯示影片標題。",
            ["SaveFolder"] = "儲存資料夾",
            ["Browse"] = "瀏覽",
            ["Quality"] = "畫質",
            ["OutputFormat"] = "輸出格式",
            ["Best4K"] = "最佳畫質（最高 4K）",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "整個播放清單",
            ["Subtitles"] = "字幕",
            ["AutoSubtitles"] = "自動字幕",
            ["Thumbnail"] = "儲存縮圖",
            ["Metadata"] = "嵌入中繼資料",
            ["OpenAfter"] = "完成後開啟資料夾",
            ["FileName"] = "檔名範本",
            ["BrowserCookies"] = "瀏覽器登入",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "下載佇列",
            ["Log"] = "記錄",
            ["StartQueue"] = "開始佇列",
            ["Remove"] = "移除所選",
            ["Clear"] = "全部清除",
            ["Cancel"] = "取消",
            ["Title"] = "標題",
            ["Status"] = "狀態",
            ["Progress"] = "進度",
            ["Date"] = "日期",
            ["Format"] = "格式",
            ["Success"] = "成功",
            ["Redownload"] = "重新下載",
            ["ClearHistory"] = "清除歷史記錄",
            ["OpenFolder"] = "開啟資料夾",
            ["UpdateTools"] = "更新工具",
            ["ClearLog"] = "清除記錄",
            ["Waiting"] = "等待中",
            ["Failed"] = "失敗",
            ["Ready"] = "就緒",
            ["CheckingInfo"] = "正在檢查資訊...",
            ["InfoCancelled"] = "資訊檢查已取消。",
            ["NoTitle"] = "無標題",
            ["Unknown"] = "未知",
            ["Channel"] = "頻道",
            ["Duration"] = "長度",
            ["PreparingDownload"] = "正在準備下載...",
            ["DownloadInProgress"] = "正在下載",
            ["RemainingTime"] = "剩餘時間",
            ["Completed"] = "已完成",
            ["Cancelled"] = "已取消",
            ["QueueComplete"] = "下載佇列已完成。",
            ["DownloadCompleteTitle"] = "下載完成",
            ["QueueCompleteNotification"] = "下載完成。成功：{0}，失敗：{1}",
            ["NotificationFailed"] = "無法顯示 Windows 完成通知。",
            ["UserCancelled"] = "使用者已取消下載。",
            ["UpdatingTools"] = "正在更新工具...",
            ["ToolsUpdated"] = "yt-dlp 與 FFmpeg 已更新。",
            ["InvalidUrl"] = "請輸入有效的影片 URL。",
            ["UrlCheck"] = "URL 檢查",
            ["ErrorOccurred"] = "發生錯誤",
            ["ErrorPrefix"] = "錯誤",
            ["ErrorHelp"] = "請檢查記錄，並在需要時更新工具。",
            ["Cancelling"] = "正在取消...",
            ["FolderDialogTitle"] = "選擇儲存資料夾",
            ["CookiesDialogTitle"] = "選擇 cookies.txt",
            ["CookiesFilter"] = "Cookies 檔案 (*.txt)|*.txt|所有檔案 (*.*)|*.*",
            ["ToolsReady"] = "所需工具已就緒",
            ["DownloadingYtDlp"] = "正在下載 yt-dlp...",
            ["DownloadingFfmpeg"] = "正在下載 FFmpeg...",
        },
        ["es"] = new()
        {
            ["WindowTitle"] = "Descargador de vídeos 4K",
            ["AppTitle"] = "Descargador de vídeos 4K",
            ["CopyrightNotice"] = "Úselo solo con vídeos propios o con permiso para descargarlos.",
            ["Language"] = "Idioma",
            ["AutoLanguage"] = "Automático (idioma de Windows)",
            ["DownloadTab"] = "Descargar",
            ["HistoryTab"] = "Historial",
            ["VideoUrl"] = "URL del vídeo",
            ["UrlInputHint"] = "Introduzca varios enlaces separados por espacios o saltos de línea.",
            ["Paste"] = "Pegar",
            ["AddQueue"] = "Añadir varios a la cola",
            ["Inspect"] = "Comprobar información",
            ["AutoClipboard"] = "Pegar automáticamente enlaces de YouTube copiados",
            ["AutoQueueClipboard"] = "Añadir automáticamente enlaces copiados a la cola",
            ["AutoStartAfterAdd"] = "Iniciar automáticamente después de añadir la URL",
            ["ClipboardQueued"] = "Se añadieron automáticamente {0} enlace(s) del portapapeles a la cola.",
            ["ClipboardPasted"] = "Se pegaron automáticamente {0} enlace(s) del portapapeles.",
            ["UrlsAdded"] = "Se añadieron {0} enlace(s) a la cola.",
            ["DuplicateUrls"] = "Los enlaces ya están en la cola.",
            ["InfoPlaceholder"] = "El título aparecerá después de comprobar la información.",
            ["SaveFolder"] = "Carpeta de destino",
            ["Browse"] = "Examinar",
            ["Quality"] = "Calidad",
            ["OutputFormat"] = "Formato de salida",
            ["Best4K"] = "Mejor calidad (hasta 4K)",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "Lista de reproducción completa",
            ["Subtitles"] = "Subtítulos",
            ["AutoSubtitles"] = "Subtítulos automáticos",
            ["Thumbnail"] = "Guardar miniatura",
            ["Metadata"] = "Incrustar metadatos",
            ["OpenAfter"] = "Abrir carpeta al terminar",
            ["FileName"] = "Plantilla de nombre",
            ["BrowserCookies"] = "Inicio de sesión del navegador",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "Cola de descargas",
            ["Log"] = "Registro",
            ["StartQueue"] = "Iniciar cola",
            ["Remove"] = "Quitar seleccionado",
            ["Clear"] = "Borrar todo",
            ["Cancel"] = "Cancelar",
            ["Title"] = "Título",
            ["Status"] = "Estado",
            ["Progress"] = "Progreso",
            ["Date"] = "Fecha",
            ["Format"] = "Formato",
            ["Success"] = "Éxito",
            ["Redownload"] = "Descargar de nuevo",
            ["ClearHistory"] = "Borrar historial",
            ["OpenFolder"] = "Abrir carpeta",
            ["UpdateTools"] = "Actualizar herramientas",
            ["ClearLog"] = "Borrar registro",
            ["Waiting"] = "En espera",
            ["Failed"] = "Error",
            ["Ready"] = "Listo",
            ["CheckingInfo"] = "Comprobando información...",
            ["InfoCancelled"] = "Comprobación cancelada.",
            ["NoTitle"] = "Sin título",
            ["Unknown"] = "Desconocido",
            ["Channel"] = "Canal",
            ["Duration"] = "Duración",
            ["PreparingDownload"] = "Preparando descarga...",
            ["DownloadInProgress"] = "Descargando",
            ["RemainingTime"] = "Restante",
            ["Completed"] = "Completado",
            ["Cancelled"] = "Cancelado",
            ["QueueComplete"] = "La cola de descargas ha finalizado.",
            ["DownloadCompleteTitle"] = "Descarga completada",
            ["QueueCompleteNotification"] = "Descargas finalizadas. Correctas: {0}, fallidas: {1}",
            ["NotificationFailed"] = "No se pudo mostrar la notificación de Windows.",
            ["UserCancelled"] = "Descarga cancelada por el usuario.",
            ["UpdatingTools"] = "Actualizando herramientas...",
            ["ToolsUpdated"] = "yt-dlp y FFmpeg actualizados.",
            ["InvalidUrl"] = "Introduzca una URL de vídeo válida.",
            ["UrlCheck"] = "Comprobar URL",
            ["ErrorOccurred"] = "Se produjo un error",
            ["ErrorPrefix"] = "Error",
            ["ErrorHelp"] = "Revise el registro y actualice las herramientas si es necesario.",
            ["Cancelling"] = "Cancelando...",
            ["FolderDialogTitle"] = "Seleccionar carpeta de destino",
            ["CookiesDialogTitle"] = "Seleccionar cookies.txt",
            ["CookiesFilter"] = "Archivos Cookies (*.txt)|*.txt|Todos los archivos (*.*)|*.*",
            ["ToolsReady"] = "Las herramientas necesarias están listas",
            ["DownloadingYtDlp"] = "Descargando yt-dlp...",
            ["DownloadingFfmpeg"] = "Descargando FFmpeg...",
        },
        ["de"] = new()
        {
            ["WindowTitle"] = "4K-Video-Downloader",
            ["AppTitle"] = "4K-Video-Downloader",
            ["CopyrightNotice"] = "Nur für eigene Videos oder Videos mit Download-Erlaubnis verwenden.",
            ["Language"] = "Sprache",
            ["AutoLanguage"] = "Automatisch (Windows-Sprache)",
            ["DownloadTab"] = "Download",
            ["HistoryTab"] = "Verlauf",
            ["VideoUrl"] = "Video-URL",
            ["UrlInputHint"] = "Mehrere Links durch Leerzeichen oder Zeilenumbrüche trennen.",
            ["Paste"] = "Einfügen",
            ["AddQueue"] = "Mehrere zur Warteschlange",
            ["Inspect"] = "Informationen prüfen",
            ["AutoClipboard"] = "Kopierte YouTube-Links automatisch einfügen",
            ["AutoQueueClipboard"] = "Kopierte Links automatisch zur Warteschlange hinzufügen",
            ["AutoStartAfterAdd"] = "Nach dem Hinzufügen der URL automatisch starten",
            ["ClipboardQueued"] = "{0} Link(s) aus der Zwischenablage wurden automatisch hinzugefügt.",
            ["ClipboardPasted"] = "{0} Link(s) automatisch aus der Zwischenablage eingefügt.",
            ["UrlsAdded"] = "{0} Link(s) zur Warteschlange hinzugefügt.",
            ["DuplicateUrls"] = "Die Links befinden sich bereits in der Warteschlange.",
            ["InfoPlaceholder"] = "Der Videotitel erscheint nach der Prüfung.",
            ["SaveFolder"] = "Speicherordner",
            ["Browse"] = "Durchsuchen",
            ["Quality"] = "Qualität",
            ["OutputFormat"] = "Ausgabeformat",
            ["Best4K"] = "Beste Qualität (bis 4K)",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "Gesamte Wiedergabeliste",
            ["Subtitles"] = "Untertitel",
            ["AutoSubtitles"] = "Automatische Untertitel",
            ["Thumbnail"] = "Miniaturbild speichern",
            ["Metadata"] = "Metadaten einbetten",
            ["OpenAfter"] = "Ordner nach Abschluss öffnen",
            ["FileName"] = "Dateinamenvorlage",
            ["BrowserCookies"] = "Browser-Anmeldung",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "Download-Warteschlange",
            ["Log"] = "Protokoll",
            ["StartQueue"] = "Warteschlange starten",
            ["Remove"] = "Auswahl entfernen",
            ["Clear"] = "Alles löschen",
            ["Cancel"] = "Abbrechen",
            ["Title"] = "Titel",
            ["Status"] = "Status",
            ["Progress"] = "Fortschritt",
            ["Date"] = "Datum",
            ["Format"] = "Format",
            ["Success"] = "Erfolg",
            ["Redownload"] = "Erneut herunterladen",
            ["ClearHistory"] = "Verlauf löschen",
            ["OpenFolder"] = "Ordner öffnen",
            ["UpdateTools"] = "Tools aktualisieren",
            ["ClearLog"] = "Protokoll löschen",
            ["Waiting"] = "Wartet",
            ["Failed"] = "Fehlgeschlagen",
            ["Ready"] = "Bereit",
            ["CheckingInfo"] = "Informationen werden geprüft...",
            ["InfoCancelled"] = "Informationsprüfung abgebrochen.",
            ["NoTitle"] = "Kein Titel",
            ["Unknown"] = "Unbekannt",
            ["Channel"] = "Kanal",
            ["Duration"] = "Dauer",
            ["PreparingDownload"] = "Download wird vorbereitet...",
            ["DownloadInProgress"] = "Wird heruntergeladen",
            ["RemainingTime"] = "Verbleibend",
            ["Completed"] = "Abgeschlossen",
            ["Cancelled"] = "Abgebrochen",
            ["QueueComplete"] = "Download-Warteschlange abgeschlossen.",
            ["DownloadCompleteTitle"] = "Download abgeschlossen",
            ["QueueCompleteNotification"] = "Downloads abgeschlossen. Erfolgreich: {0}, fehlgeschlagen: {1}",
            ["NotificationFailed"] = "Windows-Benachrichtigung konnte nicht angezeigt werden.",
            ["UserCancelled"] = "Download vom Benutzer abgebrochen.",
            ["UpdatingTools"] = "Tools werden aktualisiert...",
            ["ToolsUpdated"] = "yt-dlp und FFmpeg wurden aktualisiert.",
            ["InvalidUrl"] = "Geben Sie eine gültige Video-URL ein.",
            ["UrlCheck"] = "URL prüfen",
            ["ErrorOccurred"] = "Ein Fehler ist aufgetreten",
            ["ErrorPrefix"] = "Fehler",
            ["ErrorHelp"] = "Prüfen Sie das Protokoll und aktualisieren Sie bei Bedarf die Tools.",
            ["Cancelling"] = "Wird abgebrochen...",
            ["FolderDialogTitle"] = "Speicherordner auswählen",
            ["CookiesDialogTitle"] = "cookies.txt auswählen",
            ["CookiesFilter"] = "Cookies-Dateien (*.txt)|*.txt|Alle Dateien (*.*)|*.*",
            ["ToolsReady"] = "Erforderliche Tools sind bereit",
            ["DownloadingYtDlp"] = "yt-dlp wird heruntergeladen...",
            ["DownloadingFfmpeg"] = "FFmpeg wird heruntergeladen...",
        },
        ["fr"] = new()
        {
            ["WindowTitle"] = "Téléchargeur vidéo 4K",
            ["AppTitle"] = "Téléchargeur vidéo 4K",
            ["CopyrightNotice"] = "Utilisez-le uniquement pour les vidéos que vous possédez ou êtes autorisé à télécharger.",
            ["Language"] = "Langue",
            ["AutoLanguage"] = "Automatique (langue de Windows)",
            ["DownloadTab"] = "Télécharger",
            ["HistoryTab"] = "Historique",
            ["VideoUrl"] = "URL de la vidéo",
            ["UrlInputHint"] = "Saisissez plusieurs liens séparés par des espaces ou des retours à la ligne.",
            ["Paste"] = "Coller",
            ["AddQueue"] = "Ajouter plusieurs à la file",
            ["Inspect"] = "Vérifier les informations",
            ["AutoClipboard"] = "Coller automatiquement les liens YouTube copiés",
            ["AutoQueueClipboard"] = "Ajouter automatiquement les liens copiés à la file",
            ["AutoStartAfterAdd"] = "Démarrer automatiquement après l’ajout de l’URL",
            ["ClipboardQueued"] = "{0} lien(s) du presse-papiers ajouté(s) automatiquement à la file.",
            ["ClipboardPasted"] = "{0} lien(s) collé(s) automatiquement depuis le presse-papiers.",
            ["UrlsAdded"] = "{0} lien(s) ajouté(s) à la file.",
            ["DuplicateUrls"] = "Les liens sont déjà dans la file.",
            ["InfoPlaceholder"] = "Le titre apparaîtra après vérification des informations.",
            ["SaveFolder"] = "Dossier de destination",
            ["Browse"] = "Parcourir",
            ["Quality"] = "Qualité",
            ["OutputFormat"] = "Format de sortie",
            ["Best4K"] = "Meilleure qualité (jusqu’à 4K)",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "Liste de lecture entière",
            ["Subtitles"] = "Sous-titres",
            ["AutoSubtitles"] = "Sous-titres automatiques",
            ["Thumbnail"] = "Enregistrer la miniature",
            ["Metadata"] = "Intégrer les métadonnées",
            ["OpenAfter"] = "Ouvrir le dossier à la fin",
            ["FileName"] = "Modèle de nom de fichier",
            ["BrowserCookies"] = "Connexion au navigateur",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "File de téléchargement",
            ["Log"] = "Journal",
            ["StartQueue"] = "Démarrer la file",
            ["Remove"] = "Supprimer la sélection",
            ["Clear"] = "Tout effacer",
            ["Cancel"] = "Annuler",
            ["Title"] = "Titre",
            ["Status"] = "État",
            ["Progress"] = "Progression",
            ["Date"] = "Date",
            ["Format"] = "Format",
            ["Success"] = "Réussite",
            ["Redownload"] = "Télécharger à nouveau",
            ["ClearHistory"] = "Effacer l’historique",
            ["OpenFolder"] = "Ouvrir le dossier",
            ["UpdateTools"] = "Mettre à jour les outils",
            ["ClearLog"] = "Effacer le journal",
            ["Waiting"] = "En attente",
            ["Failed"] = "Échec",
            ["Ready"] = "Prêt",
            ["CheckingInfo"] = "Vérification des informations...",
            ["InfoCancelled"] = "Vérification annulée.",
            ["NoTitle"] = "Sans titre",
            ["Unknown"] = "Inconnu",
            ["Channel"] = "Chaîne",
            ["Duration"] = "Durée",
            ["PreparingDownload"] = "Préparation du téléchargement...",
            ["DownloadInProgress"] = "Téléchargement",
            ["RemainingTime"] = "Restant",
            ["Completed"] = "Terminé",
            ["Cancelled"] = "Annulé",
            ["QueueComplete"] = "File de téléchargement terminée.",
            ["DownloadCompleteTitle"] = "Téléchargement terminé",
            ["QueueCompleteNotification"] = "Téléchargements terminés. Réussis : {0}, échecs : {1}",
            ["NotificationFailed"] = "Impossible d’afficher la notification Windows.",
            ["UserCancelled"] = "Téléchargement annulé par l’utilisateur.",
            ["UpdatingTools"] = "Mise à jour des outils...",
            ["ToolsUpdated"] = "yt-dlp et FFmpeg ont été mis à jour.",
            ["InvalidUrl"] = "Saisissez une URL vidéo valide.",
            ["UrlCheck"] = "Vérifier l’URL",
            ["ErrorOccurred"] = "Une erreur est survenue",
            ["ErrorPrefix"] = "Erreur",
            ["ErrorHelp"] = "Consultez le journal et mettez à jour les outils si nécessaire.",
            ["Cancelling"] = "Annulation...",
            ["FolderDialogTitle"] = "Sélectionner le dossier de destination",
            ["CookiesDialogTitle"] = "Sélectionner cookies.txt",
            ["CookiesFilter"] = "Fichiers Cookies (*.txt)|*.txt|Tous les fichiers (*.*)|*.*",
            ["ToolsReady"] = "Les outils requis sont prêts",
            ["DownloadingYtDlp"] = "Téléchargement de yt-dlp...",
            ["DownloadingFfmpeg"] = "Téléchargement de FFmpeg...",
        },
        ["pt"] = new()
        {
            ["WindowTitle"] = "Baixador de vídeos 4K",
            ["AppTitle"] = "Baixador de vídeos 4K",
            ["CopyrightNotice"] = "Use somente para vídeos que você possui ou tem permissão para baixar.",
            ["Language"] = "Idioma",
            ["AutoLanguage"] = "Automático (idioma do Windows)",
            ["DownloadTab"] = "Baixar",
            ["HistoryTab"] = "Histórico",
            ["VideoUrl"] = "URL do vídeo",
            ["UrlInputHint"] = "Insira vários links separados por espaços ou linhas.",
            ["Paste"] = "Colar",
            ["AddQueue"] = "Adicionar vários à fila",
            ["Inspect"] = "Verificar informações",
            ["AutoClipboard"] = "Colar automaticamente links copiados do YouTube",
            ["AutoQueueClipboard"] = "Adicionar links copiados automaticamente à fila",
            ["AutoStartAfterAdd"] = "Iniciar automaticamente após adicionar a URL",
            ["ClipboardQueued"] = "{0} link(s) da área de transferência adicionado(s) automaticamente à fila.",
            ["ClipboardPasted"] = "{0} link(s) colado(s) automaticamente da área de transferência.",
            ["UrlsAdded"] = "{0} link(s) adicionado(s) à fila.",
            ["DuplicateUrls"] = "Os links já estão na fila.",
            ["InfoPlaceholder"] = "O título aparecerá após verificar as informações.",
            ["SaveFolder"] = "Pasta de destino",
            ["Browse"] = "Procurar",
            ["Quality"] = "Qualidade",
            ["OutputFormat"] = "Formato de saída",
            ["Best4K"] = "Melhor qualidade (até 4K)",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "Playlist inteira",
            ["Subtitles"] = "Legendas",
            ["AutoSubtitles"] = "Legendas automáticas",
            ["Thumbnail"] = "Salvar miniatura",
            ["Metadata"] = "Incorporar metadados",
            ["OpenAfter"] = "Abrir pasta ao concluir",
            ["FileName"] = "Modelo de nome de arquivo",
            ["BrowserCookies"] = "Login do navegador",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "Fila de downloads",
            ["Log"] = "Registro",
            ["StartQueue"] = "Iniciar fila",
            ["Remove"] = "Remover selecionado",
            ["Clear"] = "Limpar tudo",
            ["Cancel"] = "Cancelar",
            ["Title"] = "Título",
            ["Status"] = "Status",
            ["Progress"] = "Progresso",
            ["Date"] = "Data",
            ["Format"] = "Formato",
            ["Success"] = "Sucesso",
            ["Redownload"] = "Baixar novamente",
            ["ClearHistory"] = "Limpar histórico",
            ["OpenFolder"] = "Abrir pasta",
            ["UpdateTools"] = "Atualizar ferramentas",
            ["ClearLog"] = "Limpar registro",
            ["Waiting"] = "Aguardando",
            ["Failed"] = "Falhou",
            ["Ready"] = "Pronto",
            ["CheckingInfo"] = "Verificando informações...",
            ["InfoCancelled"] = "Verificação cancelada.",
            ["NoTitle"] = "Sem título",
            ["Unknown"] = "Desconhecido",
            ["Channel"] = "Canal",
            ["Duration"] = "Duração",
            ["PreparingDownload"] = "Preparando download...",
            ["DownloadInProgress"] = "Baixando",
            ["RemainingTime"] = "Restante",
            ["Completed"] = "Concluído",
            ["Cancelled"] = "Cancelado",
            ["QueueComplete"] = "Fila de downloads concluída.",
            ["DownloadCompleteTitle"] = "Download concluído",
            ["QueueCompleteNotification"] = "Downloads concluídos. Sucesso: {0}, falha: {1}",
            ["NotificationFailed"] = "Não foi possível mostrar a notificação do Windows.",
            ["UserCancelled"] = "Download cancelado pelo usuário.",
            ["UpdatingTools"] = "Atualizando ferramentas...",
            ["ToolsUpdated"] = "yt-dlp e FFmpeg atualizados.",
            ["InvalidUrl"] = "Insira uma URL de vídeo válida.",
            ["UrlCheck"] = "Verificar URL",
            ["ErrorOccurred"] = "Ocorreu um erro",
            ["ErrorPrefix"] = "Erro",
            ["ErrorHelp"] = "Verifique o registro e atualize as ferramentas se necessário.",
            ["Cancelling"] = "Cancelando...",
            ["FolderDialogTitle"] = "Selecionar pasta de destino",
            ["CookiesDialogTitle"] = "Selecionar cookies.txt",
            ["CookiesFilter"] = "Arquivos Cookies (*.txt)|*.txt|Todos os arquivos (*.*)|*.*",
            ["ToolsReady"] = "As ferramentas necessárias estão prontas",
            ["DownloadingYtDlp"] = "Baixando yt-dlp...",
            ["DownloadingFfmpeg"] = "Baixando FFmpeg...",
        },
        ["ru"] = new()
        {
            ["WindowTitle"] = "Загрузчик видео 4K",
            ["AppTitle"] = "Загрузчик видео 4K",
            ["CopyrightNotice"] = "Используйте только для своих видео или видео, разрешённых к скачиванию.",
            ["Language"] = "Язык",
            ["AutoLanguage"] = "Автоматически (язык Windows)",
            ["DownloadTab"] = "Загрузка",
            ["HistoryTab"] = "История",
            ["VideoUrl"] = "URL видео",
            ["UrlInputHint"] = "Введите несколько ссылок, разделяя их пробелами или строками.",
            ["Paste"] = "Вставить",
            ["AddQueue"] = "Добавить несколько в очередь",
            ["Inspect"] = "Проверить сведения",
            ["AutoClipboard"] = "Автоматически вставлять скопированные ссылки YouTube",
            ["AutoQueueClipboard"] = "Автоматически добавлять скопированные ссылки в очередь",
            ["AutoStartAfterAdd"] = "Автоматически запускать после добавления URL",
            ["ClipboardQueued"] = "Автоматически добавлено ссылок из буфера обмена: {0}.",
            ["ClipboardPasted"] = "Автоматически вставлено ссылок из буфера обмена: {0}.",
            ["UrlsAdded"] = "Добавлено ссылок в очередь: {0}.",
            ["DuplicateUrls"] = "Ссылки уже находятся в очереди.",
            ["InfoPlaceholder"] = "Название появится после проверки сведений.",
            ["SaveFolder"] = "Папка сохранения",
            ["Browse"] = "Обзор",
            ["Quality"] = "Качество",
            ["OutputFormat"] = "Формат вывода",
            ["Best4K"] = "Лучшее качество (до 4K)",
            ["Quality4K"] = "4K 2160p",
            ["QualityQHD"] = "QHD 1440p",
            ["QualityFHD"] = "FHD 1080p",
            ["QualityHD"] = "HD 720p",
            ["QualitySD"] = "SD 480p",
            ["Playlist"] = "Весь плейлист",
            ["Subtitles"] = "Субтитры",
            ["AutoSubtitles"] = "Автоматические субтитры",
            ["Thumbnail"] = "Сохранить миниатюру",
            ["Metadata"] = "Встроить метаданные",
            ["OpenAfter"] = "Открыть папку после завершения",
            ["FileName"] = "Шаблон имени файла",
            ["BrowserCookies"] = "Вход через браузер",
            ["CookiesFile"] = "cookies.txt",
            ["Queue"] = "Очередь загрузки",
            ["Log"] = "Журнал",
            ["StartQueue"] = "Запустить очередь",
            ["Remove"] = "Удалить выбранное",
            ["Clear"] = "Очистить всё",
            ["Cancel"] = "Отмена",
            ["Title"] = "Название",
            ["Status"] = "Состояние",
            ["Progress"] = "Прогресс",
            ["Date"] = "Дата",
            ["Format"] = "Формат",
            ["Success"] = "Успех",
            ["Redownload"] = "Скачать снова",
            ["ClearHistory"] = "Очистить историю",
            ["OpenFolder"] = "Открыть папку",
            ["UpdateTools"] = "Обновить инструменты",
            ["ClearLog"] = "Очистить журнал",
            ["Waiting"] = "Ожидание",
            ["Failed"] = "Ошибка",
            ["Ready"] = "Готово",
            ["CheckingInfo"] = "Проверка сведений...",
            ["InfoCancelled"] = "Проверка сведений отменена.",
            ["NoTitle"] = "Без названия",
            ["Unknown"] = "Неизвестно",
            ["Channel"] = "Канал",
            ["Duration"] = "Длительность",
            ["PreparingDownload"] = "Подготовка загрузки...",
            ["DownloadInProgress"] = "Загрузка",
            ["RemainingTime"] = "Осталось",
            ["Completed"] = "Завершено",
            ["Cancelled"] = "Отменено",
            ["QueueComplete"] = "Очередь загрузки завершена.",
            ["DownloadCompleteTitle"] = "Загрузка завершена",
            ["QueueCompleteNotification"] = "Загрузки завершены. Успешно: {0}, ошибок: {1}",
            ["NotificationFailed"] = "Не удалось показать уведомление Windows.",
            ["UserCancelled"] = "Загрузка отменена пользователем.",
            ["UpdatingTools"] = "Обновление инструментов...",
            ["ToolsUpdated"] = "yt-dlp и FFmpeg обновлены.",
            ["InvalidUrl"] = "Введите допустимый URL видео.",
            ["UrlCheck"] = "Проверка URL",
            ["ErrorOccurred"] = "Произошла ошибка",
            ["ErrorPrefix"] = "Ошибка",
            ["ErrorHelp"] = "Проверьте журнал и при необходимости обновите инструменты.",
            ["Cancelling"] = "Отмена...",
            ["FolderDialogTitle"] = "Выберите папку сохранения",
            ["CookiesDialogTitle"] = "Выберите cookies.txt",
            ["CookiesFilter"] = "Файлы Cookies (*.txt)|*.txt|Все файлы (*.*)|*.*",
            ["ToolsReady"] = "Необходимые инструменты готовы",
            ["DownloadingYtDlp"] = "Загрузка yt-dlp...",
            ["DownloadingFfmpeg"] = "Загрузка FFmpeg...",
        },
    };


    static LocalizationManager()
    {
        AddLanguage("it", new()
        {
            ["WindowTitle"]="Downloader video 4K", ["AppTitle"]="Downloader video 4K", ["CopyrightNotice"]="Usa il programma solo per video di tua proprietà o per cui hai il permesso di download.", ["Language"]="Lingua", ["AutoLanguage"]="Automatica (lingua di Windows)",
            ["DownloadTab"]="Download", ["HistoryTab"]="Cronologia", ["VideoUrl"]="URL video", ["UrlInputHint"]="Inserisci più link separati da spazi o righe.", ["Paste"]="Incolla", ["AddQueue"]="Aggiungi più elementi alla coda", ["Inspect"]="Controlla informazioni", ["AutoClipboard"]="Incolla automaticamente i link YouTube copiati", ["ClipboardPasted"]="Incollati automaticamente {0} link dagli appunti.", ["UrlsAdded"]="Aggiunti {0} link alla coda.", ["DuplicateUrls"]="I link sono già presenti nella coda.",
            ["SaveFolder"]="Cartella di salvataggio", ["Browse"]="Sfoglia", ["Quality"]="Qualità", ["OutputFormat"]="Formato di output", ["Playlist"]="Intera playlist", ["Subtitles"]="Sottotitoli", ["AutoSubtitles"]="Sottotitoli automatici", ["Thumbnail"]="Salva miniatura", ["Metadata"]="Incorpora metadati", ["OpenAfter"]="Apri la cartella al termine", ["FileName"]="Modello nome file", ["BrowserCookies"]="Accesso browser", ["Queue"]="Coda download", ["Log"]="Registro", ["StartQueue"]="Avvia coda", ["Remove"]="Rimuovi selezionati", ["Clear"]="Cancella tutto", ["Cancel"]="Annulla", ["Title"]="Titolo", ["Status"]="Stato", ["Progress"]="Avanzamento", ["Date"]="Data", ["Format"]="Formato", ["Success"]="Riuscito", ["Waiting"]="In attesa", ["Failed"]="Non riuscito", ["Ready"]="Pronto", ["Completed"]="Completato", ["Cancelled"]="Annullato", ["DownloadInProgress"]="Download in corso", ["RemainingTime"]="Tempo rimanente", ["DownloadCompleteTitle"]="Download completato", ["QueueCompleteNotification"]="Download terminati. Riusciti: {0}, non riusciti: {1}", ["InvalidUrl"]="Inserisci un URL video valido.", ["ErrorOccurred"]="Si è verificato un errore", ["UpdatingTools"]="Aggiornamento strumenti...", ["ToolsUpdated"]="yt-dlp e FFmpeg sono stati aggiornati.", ["OpenFolder"]="Apri cartella", ["UpdateTools"]="Aggiorna strumenti", ["ClearLog"]="Cancella registro"
        });
        AddLanguage("nl", new()
        {
            ["WindowTitle"]="4K-videodownloader", ["AppTitle"]="4K-videodownloader", ["CopyrightNotice"]="Gebruik dit alleen voor video's die van u zijn of waarvoor u toestemming hebt om ze te downloaden.", ["Language"]="Taal", ["AutoLanguage"]="Automatisch (Windows-taal)", ["DownloadTab"]="Downloaden", ["HistoryTab"]="Geschiedenis", ["VideoUrl"]="Video-URL", ["UrlInputHint"]="Voer meerdere links in, gescheiden door spaties of nieuwe regels.", ["Paste"]="Plakken", ["AddQueue"]="Meerdere aan wachtrij toevoegen", ["Inspect"]="Info controleren", ["AutoClipboard"]="Gekopieerde YouTube-links automatisch plakken", ["ClipboardPasted"]="Automatisch {0} link(s) van het klembord geplakt.", ["UrlsAdded"]="{0} link(s) aan de wachtrij toegevoegd.", ["DuplicateUrls"]="De links staan al in de wachtrij.", ["SaveFolder"]="Opslagmap", ["Browse"]="Bladeren", ["Quality"]="Kwaliteit", ["OutputFormat"]="Uitvoerformaat", ["Playlist"]="Volledige afspeellijst", ["Subtitles"]="Ondertiteling", ["AutoSubtitles"]="Automatische ondertiteling", ["Thumbnail"]="Miniatuur opslaan", ["Metadata"]="Metadata insluiten", ["OpenAfter"]="Map openen na voltooiing", ["FileName"]="Bestandsnaamsjabloon", ["BrowserCookies"]="Browseraanmelding", ["Queue"]="Downloadwachtrij", ["Log"]="Logboek", ["StartQueue"]="Wachtrij starten", ["Remove"]="Selectie verwijderen", ["Clear"]="Alles wissen", ["Cancel"]="Annuleren", ["Title"]="Titel", ["Status"]="Status", ["Progress"]="Voortgang", ["Date"]="Datum", ["Format"]="Formaat", ["Success"]="Geslaagd", ["Waiting"]="Wachten", ["Failed"]="Mislukt", ["Ready"]="Gereed", ["Completed"]="Voltooid", ["Cancelled"]="Geannuleerd", ["DownloadInProgress"]="Downloaden", ["RemainingTime"]="Resterend", ["DownloadCompleteTitle"]="Download voltooid", ["QueueCompleteNotification"]="Downloads voltooid. Geslaagd: {0}, mislukt: {1}", ["InvalidUrl"]="Voer een geldige video-URL in.", ["ErrorOccurred"]="Er is een fout opgetreden", ["UpdatingTools"]="Hulpmiddelen bijwerken...", ["ToolsUpdated"]="yt-dlp en FFmpeg zijn bijgewerkt.", ["OpenFolder"]="Map openen", ["UpdateTools"]="Hulpmiddelen bijwerken", ["ClearLog"]="Logboek wissen"
        });
        AddLanguage("pl", new()
        {
            ["WindowTitle"]="Program do pobierania wideo 4K", ["AppTitle"]="Program do pobierania wideo 4K", ["CopyrightNotice"]="Używaj tylko do filmów, których jesteś właścicielem lub masz zgodę na pobranie.", ["Language"]="Język", ["AutoLanguage"]="Automatycznie (język Windows)", ["DownloadTab"]="Pobieranie", ["HistoryTab"]="Historia", ["VideoUrl"]="Adres URL filmu", ["UrlInputHint"]="Wprowadź wiele linków oddzielonych spacjami lub nowymi wierszami.", ["Paste"]="Wklej", ["AddQueue"]="Dodaj wiele do kolejki", ["Inspect"]="Sprawdź informacje", ["AutoClipboard"]="Automatycznie wklejaj skopiowane linki YouTube", ["ClipboardPasted"]="Automatycznie wklejono {0} linków ze schowka.", ["UrlsAdded"]="Dodano {0} linków do kolejki.", ["DuplicateUrls"]="Linki są już w kolejce.", ["SaveFolder"]="Folder zapisu", ["Browse"]="Przeglądaj", ["Quality"]="Jakość", ["OutputFormat"]="Format wyjściowy", ["Playlist"]="Cała playlista", ["Subtitles"]="Napisy", ["AutoSubtitles"]="Napisy automatyczne", ["Thumbnail"]="Zapisz miniaturę", ["Metadata"]="Osadź metadane", ["OpenAfter"]="Otwórz folder po zakończeniu", ["FileName"]="Szablon nazwy pliku", ["BrowserCookies"]="Logowanie przez przeglądarkę", ["Queue"]="Kolejka pobierania", ["Log"]="Dziennik", ["StartQueue"]="Uruchom kolejkę", ["Remove"]="Usuń zaznaczone", ["Clear"]="Wyczyść wszystko", ["Cancel"]="Anuluj", ["Title"]="Tytuł", ["Status"]="Stan", ["Progress"]="Postęp", ["Date"]="Data", ["Format"]="Format", ["Success"]="Sukces", ["Waiting"]="Oczekiwanie", ["Failed"]="Niepowodzenie", ["Ready"]="Gotowe", ["Completed"]="Ukończono", ["Cancelled"]="Anulowano", ["DownloadInProgress"]="Pobieranie", ["RemainingTime"]="Pozostało", ["DownloadCompleteTitle"]="Pobieranie zakończone", ["QueueCompleteNotification"]="Pobieranie zakończone. Sukces: {0}, błędy: {1}", ["InvalidUrl"]="Wprowadź prawidłowy adres URL filmu.", ["ErrorOccurred"]="Wystąpił błąd", ["UpdatingTools"]="Aktualizowanie narzędzi...", ["ToolsUpdated"]="Zaktualizowano yt-dlp i FFmpeg.", ["OpenFolder"]="Otwórz folder", ["UpdateTools"]="Aktualizuj narzędzia", ["ClearLog"]="Wyczyść dziennik"
        });
        AddLanguage("tr", new()
        {
            ["WindowTitle"]="4K Video İndirici", ["AppTitle"]="4K Video İndirici", ["CopyrightNotice"]="Yalnızca sahibi olduğunuz veya indirme izni bulunan videolar için kullanın.", ["Language"]="Dil", ["AutoLanguage"]="Otomatik (Windows dili)", ["DownloadTab"]="İndir", ["HistoryTab"]="Geçmiş", ["VideoUrl"]="Video URL'si", ["UrlInputHint"]="Birden fazla bağlantıyı boşluk veya yeni satırlarla ayırarak girin.", ["Paste"]="Yapıştır", ["AddQueue"]="Birden fazlasını kuyruğa ekle", ["Inspect"]="Bilgiyi kontrol et", ["AutoClipboard"]="Kopyalanan YouTube bağlantılarını otomatik yapıştır", ["ClipboardPasted"]="Panodan {0} bağlantı otomatik yapıştırıldı.", ["UrlsAdded"]="Kuyruğa {0} bağlantı eklendi.", ["DuplicateUrls"]="Bağlantılar zaten kuyrukta.", ["SaveFolder"]="Kayıt klasörü", ["Browse"]="Gözat", ["Quality"]="Kalite", ["OutputFormat"]="Çıkış biçimi", ["Playlist"]="Tüm oynatma listesi", ["Subtitles"]="Altyazılar", ["AutoSubtitles"]="Otomatik altyazılar", ["Thumbnail"]="Küçük resmi kaydet", ["Metadata"]="Meta veriyi göm", ["OpenAfter"]="Tamamlanınca klasörü aç", ["FileName"]="Dosya adı şablonu", ["BrowserCookies"]="Tarayıcı oturumu", ["Queue"]="İndirme kuyruğu", ["Log"]="Günlük", ["StartQueue"]="Kuyruğu başlat", ["Remove"]="Seçilenleri kaldır", ["Clear"]="Tümünü temizle", ["Cancel"]="İptal", ["Title"]="Başlık", ["Status"]="Durum", ["Progress"]="İlerleme", ["Date"]="Tarih", ["Format"]="Biçim", ["Success"]="Başarılı", ["Waiting"]="Bekliyor", ["Failed"]="Başarısız", ["Ready"]="Hazır", ["Completed"]="Tamamlandı", ["Cancelled"]="İptal edildi", ["DownloadInProgress"]="İndiriliyor", ["RemainingTime"]="Kalan", ["DownloadCompleteTitle"]="İndirme tamamlandı", ["QueueCompleteNotification"]="İndirmeler tamamlandı. Başarılı: {0}, başarısız: {1}", ["InvalidUrl"]="Geçerli bir video URL'si girin.", ["ErrorOccurred"]="Bir hata oluştu", ["UpdatingTools"]="Araçlar güncelleniyor...", ["ToolsUpdated"]="yt-dlp ve FFmpeg güncellendi.", ["OpenFolder"]="Klasörü aç", ["UpdateTools"]="Araçları güncelle", ["ClearLog"]="Günlüğü temizle"
        });
        AddLanguage("uk", new()
        {
            ["WindowTitle"]="Завантажувач відео 4K", ["AppTitle"]="Завантажувач відео 4K", ["CopyrightNotice"]="Використовуйте лише для власних відео або відео, дозволених до завантаження.", ["Language"]="Мова", ["AutoLanguage"]="Автоматично (мова Windows)", ["DownloadTab"]="Завантаження", ["HistoryTab"]="Історія", ["VideoUrl"]="URL відео", ["UrlInputHint"]="Введіть кілька посилань, розділених пробілами або новими рядками.", ["Paste"]="Вставити", ["AddQueue"]="Додати кілька до черги", ["Inspect"]="Перевірити інформацію", ["AutoClipboard"]="Автоматично вставляти скопійовані посилання YouTube", ["ClipboardPasted"]="Автоматично вставлено посилань: {0}.", ["UrlsAdded"]="Додано посилань до черги: {0}.", ["DuplicateUrls"]="Посилання вже є в черзі.", ["SaveFolder"]="Папка збереження", ["Browse"]="Огляд", ["Quality"]="Якість", ["OutputFormat"]="Формат виводу", ["Playlist"]="Увесь список відтворення", ["Subtitles"]="Субтитри", ["AutoSubtitles"]="Автоматичні субтитри", ["Thumbnail"]="Зберегти мініатюру", ["Metadata"]="Вбудувати метадані", ["OpenAfter"]="Відкрити папку після завершення", ["FileName"]="Шаблон імені файлу", ["BrowserCookies"]="Вхід через браузер", ["Queue"]="Черга завантажень", ["Log"]="Журнал", ["StartQueue"]="Запустити чергу", ["Remove"]="Видалити вибране", ["Clear"]="Очистити все", ["Cancel"]="Скасувати", ["Title"]="Назва", ["Status"]="Стан", ["Progress"]="Перебіг", ["Date"]="Дата", ["Format"]="Формат", ["Success"]="Успішно", ["Waiting"]="Очікування", ["Failed"]="Помилка", ["Ready"]="Готово", ["Completed"]="Завершено", ["Cancelled"]="Скасовано", ["DownloadInProgress"]="Завантаження", ["RemainingTime"]="Залишилось", ["DownloadCompleteTitle"]="Завантаження завершено", ["QueueCompleteNotification"]="Завантаження завершено. Успішно: {0}, помилок: {1}", ["InvalidUrl"]="Введіть правильний URL відео.", ["ErrorOccurred"]="Сталася помилка", ["UpdatingTools"]="Оновлення інструментів...", ["ToolsUpdated"]="yt-dlp і FFmpeg оновлено.", ["OpenFolder"]="Відкрити папку", ["UpdateTools"]="Оновити інструменти", ["ClearLog"]="Очистити журнал"
        });
        AddLanguage("vi", new()
        {
            ["WindowTitle"]="Trình tải video 4K", ["AppTitle"]="Trình tải video 4K", ["CopyrightNotice"]="Chỉ sử dụng cho video thuộc sở hữu của bạn hoặc được phép tải xuống.", ["Language"]="Ngôn ngữ", ["AutoLanguage"]="Tự động (ngôn ngữ Windows)", ["DownloadTab"]="Tải xuống", ["HistoryTab"]="Lịch sử", ["VideoUrl"]="URL video", ["UrlInputHint"]="Nhập nhiều liên kết, phân cách bằng dấu cách hoặc dòng mới.", ["Paste"]="Dán", ["AddQueue"]="Thêm nhiều mục vào hàng đợi", ["Inspect"]="Kiểm tra thông tin", ["AutoClipboard"]="Tự động dán liên kết YouTube đã sao chép", ["ClipboardPasted"]="Đã tự động dán {0} liên kết từ bảng tạm.", ["UrlsAdded"]="Đã thêm {0} liên kết vào hàng đợi.", ["DuplicateUrls"]="Các liên kết đã có trong hàng đợi.", ["SaveFolder"]="Thư mục lưu", ["Browse"]="Duyệt", ["Quality"]="Chất lượng", ["OutputFormat"]="Định dạng đầu ra", ["Playlist"]="Toàn bộ danh sách phát", ["Subtitles"]="Phụ đề", ["AutoSubtitles"]="Phụ đề tự động", ["Thumbnail"]="Lưu hình thu nhỏ", ["Metadata"]="Nhúng siêu dữ liệu", ["OpenAfter"]="Mở thư mục khi hoàn tất", ["FileName"]="Mẫu tên tệp", ["BrowserCookies"]="Đăng nhập trình duyệt", ["Queue"]="Hàng đợi tải xuống", ["Log"]="Nhật ký", ["StartQueue"]="Bắt đầu hàng đợi", ["Remove"]="Xóa mục đã chọn", ["Clear"]="Xóa tất cả", ["Cancel"]="Hủy", ["Title"]="Tiêu đề", ["Status"]="Trạng thái", ["Progress"]="Tiến trình", ["Date"]="Ngày", ["Format"]="Định dạng", ["Success"]="Thành công", ["Waiting"]="Đang chờ", ["Failed"]="Thất bại", ["Ready"]="Sẵn sàng", ["Completed"]="Hoàn tất", ["Cancelled"]="Đã hủy", ["DownloadInProgress"]="Đang tải", ["RemainingTime"]="Còn lại", ["DownloadCompleteTitle"]="Tải xuống hoàn tất", ["QueueCompleteNotification"]="Đã tải xong. Thành công: {0}, thất bại: {1}", ["InvalidUrl"]="Hãy nhập URL video hợp lệ.", ["ErrorOccurred"]="Đã xảy ra lỗi", ["UpdatingTools"]="Đang cập nhật công cụ...", ["ToolsUpdated"]="Đã cập nhật yt-dlp và FFmpeg.", ["OpenFolder"]="Mở thư mục", ["UpdateTools"]="Cập nhật công cụ", ["ClearLog"]="Xóa nhật ký"
        });
        AddLanguage("id", new()
        {
            ["WindowTitle"]="Pengunduh Video 4K", ["AppTitle"]="Pengunduh Video 4K", ["CopyrightNotice"]="Gunakan hanya untuk video milik Anda atau yang diizinkan untuk diunduh.", ["Language"]="Bahasa", ["AutoLanguage"]="Otomatis (bahasa Windows)", ["DownloadTab"]="Unduh", ["HistoryTab"]="Riwayat", ["VideoUrl"]="URL video", ["UrlInputHint"]="Masukkan beberapa tautan yang dipisahkan spasi atau baris baru.", ["Paste"]="Tempel", ["AddQueue"]="Tambahkan beberapa ke antrean", ["Inspect"]="Periksa info", ["AutoClipboard"]="Tempel otomatis tautan YouTube yang disalin", ["ClipboardPasted"]="Otomatis menempelkan {0} tautan dari papan klip.", ["UrlsAdded"]="Menambahkan {0} tautan ke antrean.", ["DuplicateUrls"]="Tautan sudah ada di antrean.", ["SaveFolder"]="Folder penyimpanan", ["Browse"]="Telusuri", ["Quality"]="Kualitas", ["OutputFormat"]="Format keluaran", ["Playlist"]="Seluruh daftar putar", ["Subtitles"]="Subtitle", ["AutoSubtitles"]="Subtitle otomatis", ["Thumbnail"]="Simpan gambar mini", ["Metadata"]="Sematkan metadata", ["OpenAfter"]="Buka folder setelah selesai", ["FileName"]="Templat nama file", ["BrowserCookies"]="Login browser", ["Queue"]="Antrean unduhan", ["Log"]="Log", ["StartQueue"]="Mulai antrean", ["Remove"]="Hapus yang dipilih", ["Clear"]="Hapus semua", ["Cancel"]="Batal", ["Title"]="Judul", ["Status"]="Status", ["Progress"]="Progres", ["Date"]="Tanggal", ["Format"]="Format", ["Success"]="Berhasil", ["Waiting"]="Menunggu", ["Failed"]="Gagal", ["Ready"]="Siap", ["Completed"]="Selesai", ["Cancelled"]="Dibatalkan", ["DownloadInProgress"]="Mengunduh", ["RemainingTime"]="Tersisa", ["DownloadCompleteTitle"]="Unduhan selesai", ["QueueCompleteNotification"]="Unduhan selesai. Berhasil: {0}, gagal: {1}", ["InvalidUrl"]="Masukkan URL video yang valid.", ["ErrorOccurred"]="Terjadi kesalahan", ["UpdatingTools"]="Memperbarui alat...", ["ToolsUpdated"]="yt-dlp dan FFmpeg telah diperbarui.", ["OpenFolder"]="Buka folder", ["UpdateTools"]="Perbarui alat", ["ClearLog"]="Hapus log"
        });
        AddLanguage("th", new()
        {
            ["WindowTitle"]="โปรแกรมดาวน์โหลดวิดีโอ 4K", ["AppTitle"]="โปรแกรมดาวน์โหลดวิดีโอ 4K", ["CopyrightNotice"]="ใช้เฉพาะกับวิดีโอที่คุณเป็นเจ้าของหรือได้รับอนุญาตให้ดาวน์โหลด", ["Language"]="ภาษา", ["AutoLanguage"]="อัตโนมัติ (ภาษาของ Windows)", ["DownloadTab"]="ดาวน์โหลด", ["HistoryTab"]="ประวัติ", ["VideoUrl"]="URL วิดีโอ", ["UrlInputHint"]="ป้อนหลายลิงก์โดยคั่นด้วยช่องว่างหรือบรรทัดใหม่", ["Paste"]="วาง", ["AddQueue"]="เพิ่มหลายรายการลงคิว", ["Inspect"]="ตรวจสอบข้อมูล", ["AutoClipboard"]="วางลิงก์ YouTube ที่คัดลอกโดยอัตโนมัติ", ["ClipboardPasted"]="วาง {0} ลิงก์จากคลิปบอร์ดโดยอัตโนมัติ", ["UrlsAdded"]="เพิ่ม {0} ลิงก์ลงในคิวแล้ว", ["DuplicateUrls"]="ลิงก์อยู่ในคิวแล้ว", ["SaveFolder"]="โฟลเดอร์บันทึก", ["Browse"]="เรียกดู", ["Quality"]="คุณภาพ", ["OutputFormat"]="รูปแบบเอาต์พุต", ["Playlist"]="เพลย์ลิสต์ทั้งหมด", ["Subtitles"]="คำบรรยาย", ["AutoSubtitles"]="คำบรรยายอัตโนมัติ", ["Thumbnail"]="บันทึกภาพขนาดย่อ", ["Metadata"]="ฝังข้อมูลเมตา", ["OpenAfter"]="เปิดโฟลเดอร์เมื่อเสร็จ", ["FileName"]="รูปแบบชื่อไฟล์", ["BrowserCookies"]="เข้าสู่ระบบผ่านเบราว์เซอร์", ["Queue"]="คิวดาวน์โหลด", ["Log"]="บันทึก", ["StartQueue"]="เริ่มคิว", ["Remove"]="ลบที่เลือก", ["Clear"]="ล้างทั้งหมด", ["Cancel"]="ยกเลิก", ["Title"]="ชื่อ", ["Status"]="สถานะ", ["Progress"]="ความคืบหน้า", ["Date"]="วันที่", ["Format"]="รูปแบบ", ["Success"]="สำเร็จ", ["Waiting"]="กำลังรอ", ["Failed"]="ล้มเหลว", ["Ready"]="พร้อม", ["Completed"]="เสร็จสิ้น", ["Cancelled"]="ยกเลิกแล้ว", ["DownloadInProgress"]="กำลังดาวน์โหลด", ["RemainingTime"]="เหลือ", ["DownloadCompleteTitle"]="ดาวน์โหลดเสร็จสิ้น", ["QueueCompleteNotification"]="ดาวน์โหลดเสร็จแล้ว สำเร็จ: {0}, ล้มเหลว: {1}", ["InvalidUrl"]="ป้อน URL วิดีโอที่ถูกต้อง", ["ErrorOccurred"]="เกิดข้อผิดพลาด", ["UpdatingTools"]="กำลังอัปเดตเครื่องมือ...", ["ToolsUpdated"]="อัปเดต yt-dlp และ FFmpeg แล้ว", ["OpenFolder"]="เปิดโฟลเดอร์", ["UpdateTools"]="อัปเดตเครื่องมือ", ["ClearLog"]="ล้างบันทึก"
        });
        AddLanguage("ar", new()
        {
            ["WindowTitle"]="منزّل فيديو 4K", ["AppTitle"]="منزّل فيديو 4K", ["CopyrightNotice"]="استخدمه فقط مع الفيديوهات التي تملكها أو لديك إذن بتنزيلها.", ["Language"]="اللغة", ["AutoLanguage"]="تلقائي (لغة Windows)", ["DownloadTab"]="تنزيل", ["HistoryTab"]="السجل", ["VideoUrl"]="رابط الفيديو", ["UrlInputHint"]="أدخل عدة روابط مفصولة بمسافات أو أسطر جديدة.", ["Paste"]="لصق", ["AddQueue"]="إضافة عدة روابط إلى قائمة الانتظار", ["Inspect"]="فحص المعلومات", ["AutoClipboard"]="لصق روابط YouTube المنسوخة تلقائيًا", ["ClipboardPasted"]="تم لصق {0} رابط تلقائيًا من الحافظة.", ["UrlsAdded"]="تمت إضافة {0} رابط إلى قائمة الانتظار.", ["DuplicateUrls"]="الروابط موجودة بالفعل في قائمة الانتظار.", ["SaveFolder"]="مجلد الحفظ", ["Browse"]="استعراض", ["Quality"]="الجودة", ["OutputFormat"]="تنسيق الإخراج", ["Playlist"]="قائمة التشغيل كاملة", ["Subtitles"]="الترجمة", ["AutoSubtitles"]="ترجمة تلقائية", ["Thumbnail"]="حفظ الصورة المصغرة", ["Metadata"]="تضمين البيانات الوصفية", ["OpenAfter"]="فتح المجلد عند الانتهاء", ["FileName"]="قالب اسم الملف", ["BrowserCookies"]="تسجيل دخول المتصفح", ["Queue"]="قائمة التنزيل", ["Log"]="السجل", ["StartQueue"]="بدء قائمة الانتظار", ["Remove"]="إزالة المحدد", ["Clear"]="مسح الكل", ["Cancel"]="إلغاء", ["Title"]="العنوان", ["Status"]="الحالة", ["Progress"]="التقدم", ["Date"]="التاريخ", ["Format"]="التنسيق", ["Success"]="نجاح", ["Waiting"]="انتظار", ["Failed"]="فشل", ["Ready"]="جاهز", ["Completed"]="مكتمل", ["Cancelled"]="ملغى", ["DownloadInProgress"]="جارٍ التنزيل", ["RemainingTime"]="المتبقي", ["DownloadCompleteTitle"]="اكتمل التنزيل", ["QueueCompleteNotification"]="انتهت التنزيلات. ناجح: {0}، فاشل: {1}", ["InvalidUrl"]="أدخل رابط فيديو صالحًا.", ["ErrorOccurred"]="حدث خطأ", ["UpdatingTools"]="جارٍ تحديث الأدوات...", ["ToolsUpdated"]="تم تحديث yt-dlp وFFmpeg.", ["OpenFolder"]="فتح المجلد", ["UpdateTools"]="تحديث الأدوات", ["ClearLog"]="مسح السجل"
        });
        AddLanguage("hi", new()
        {
            ["WindowTitle"]="4K वीडियो डाउनलोडर", ["AppTitle"]="4K वीडियो डाउनलोडर", ["CopyrightNotice"]="केवल उन वीडियो के लिए उपयोग करें जिनके आप मालिक हैं या जिन्हें डाउनलोड करने की अनुमति है।", ["Language"]="भाषा", ["AutoLanguage"]="स्वचालित (Windows भाषा)", ["DownloadTab"]="डाउनलोड", ["HistoryTab"]="इतिहास", ["VideoUrl"]="वीडियो URL", ["UrlInputHint"]="कई लिंक स्पेस या नई पंक्ति से अलग करके दर्ज करें।", ["Paste"]="पेस्ट", ["AddQueue"]="कई लिंक कतार में जोड़ें", ["Inspect"]="जानकारी जाँचें", ["AutoClipboard"]="कॉपी किए गए YouTube लिंक अपने आप पेस्ट करें", ["ClipboardPasted"]="क्लिपबोर्ड से {0} लिंक अपने आप पेस्ट किए गए।", ["UrlsAdded"]="कतार में {0} लिंक जोड़े गए।", ["DuplicateUrls"]="लिंक पहले से कतार में हैं।", ["SaveFolder"]="सहेजने का फ़ोल्डर", ["Browse"]="ब्राउज़", ["Quality"]="गुणवत्ता", ["OutputFormat"]="आउटपुट प्रारूप", ["Playlist"]="पूरी प्लेलिस्ट", ["Subtitles"]="उपशीर्षक", ["AutoSubtitles"]="स्वचालित उपशीर्षक", ["Thumbnail"]="थंबनेल सहेजें", ["Metadata"]="मेटाडेटा जोड़ें", ["OpenAfter"]="पूरा होने पर फ़ोल्डर खोलें", ["FileName"]="फ़ाइल नाम टेम्पलेट", ["BrowserCookies"]="ब्राउज़र लॉगिन", ["Queue"]="डाउनलोड कतार", ["Log"]="लॉग", ["StartQueue"]="कतार शुरू करें", ["Remove"]="चयनित हटाएँ", ["Clear"]="सब साफ़ करें", ["Cancel"]="रद्द करें", ["Title"]="शीर्षक", ["Status"]="स्थिति", ["Progress"]="प्रगति", ["Date"]="तारीख", ["Format"]="प्रारूप", ["Success"]="सफल", ["Waiting"]="प्रतीक्षा", ["Failed"]="विफल", ["Ready"]="तैयार", ["Completed"]="पूर्ण", ["Cancelled"]="रद्द", ["DownloadInProgress"]="डाउनलोड हो रहा है", ["RemainingTime"]="शेष", ["DownloadCompleteTitle"]="डाउनलोड पूर्ण", ["QueueCompleteNotification"]="डाउनलोड पूरे हुए। सफल: {0}, विफल: {1}", ["InvalidUrl"]="मान्य वीडियो URL दर्ज करें।", ["ErrorOccurred"]="एक त्रुटि हुई", ["UpdatingTools"]="टूल अपडेट हो रहे हैं...", ["ToolsUpdated"]="yt-dlp और FFmpeg अपडेट किए गए।", ["OpenFolder"]="फ़ोल्डर खोलें", ["UpdateTools"]="टूल अपडेट करें", ["ClearLog"]="लॉग साफ़ करें"
        });

        SetAutomationText("it", "Aggiungi automaticamente i link copiati alla coda", "Avvia automaticamente dopo l’aggiunta dell’URL", "Aggiunti automaticamente {0} link dagli appunti alla coda.");
        SetAutomationText("nl", "Gekopieerde links automatisch aan wachtrij toevoegen", "Automatisch starten na toevoegen van URL", "Automatisch {0} klembordlink(s) aan de wachtrij toegevoegd.");
        SetAutomationText("pl", "Automatycznie dodawaj skopiowane linki do kolejki", "Uruchom automatycznie po dodaniu adresu URL", "Automatycznie dodano do kolejki {0} linków ze schowka.");
        SetAutomationText("tr", "Kopyalanan bağlantıları otomatik olarak kuyruğa ekle", "URL eklendikten sonra otomatik başlat", "Panodan {0} bağlantı otomatik olarak kuyruğa eklendi.");
        SetAutomationText("uk", "Автоматично додавати скопійовані посилання до черги", "Автоматично запускати після додавання URL", "Автоматично додано до черги посилань із буфера: {0}.");
        SetAutomationText("vi", "Tự động thêm liên kết đã sao chép vào hàng đợi", "Tự động bắt đầu sau khi thêm URL", "Đã tự động thêm {0} liên kết từ bảng tạm vào hàng đợi.");
        SetAutomationText("id", "Tambahkan tautan yang disalin ke antrean secara otomatis", "Mulai otomatis setelah URL ditambahkan", "Otomatis menambahkan {0} tautan papan klip ke antrean.");
        SetAutomationText("th", "เพิ่มลิงก์ที่คัดลอกลงคิวโดยอัตโนมัติ", "เริ่มดาวน์โหลดอัตโนมัติหลังเพิ่ม URL", "เพิ่มลิงก์จากคลิปบอร์ด {0} รายการลงคิวโดยอัตโนมัติแล้ว");
        SetAutomationText("ar", "إضافة الروابط المنسوخة تلقائيًا إلى قائمة الانتظار", "بدء التنزيل تلقائيًا بعد إضافة الرابط", "تمت إضافة {0} رابط من الحافظة تلقائيًا إلى قائمة الانتظار.");
        SetAutomationText("hi", "कॉपी किए गए लिंक अपने आप कतार में जोड़ें", "URL जोड़ने के बाद अपने आप डाउनलोड शुरू करें", "क्लिपबोर्ड से {0} लिंक अपने आप कतार में जोड़े गए।");

    }


    private static void SetAutomationText(string code, string autoQueue, string autoStart, string queuedMessage)
    {
        if (!D.TryGetValue(code, out var language)) return;
        language["AutoQueueClipboard"] = autoQueue;
        language["AutoStartAfterAdd"] = autoStart;
        language["ClipboardQueued"] = queuedMessage;
    }

    private static void AddLanguage(string code, Dictionary<string, string> translations)
    {
        var merged = new Dictionary<string, string>(D["en"]);
        foreach (var pair in translations) merged[pair.Key] = pair.Value;
        D[code] = merged;
    }

    public static string CurrentLanguage { get; private set; } = "en";
    public static IReadOnlyCollection<string> SupportedLanguages => D.Keys;

    public static string ResolveSystemLanguage(CultureInfo? culture = null)
    {
        culture ??= CultureInfo.CurrentUICulture;
        var name = culture.Name;
        var two = culture.TwoLetterISOLanguageName;
        if (two == "zh")
            return name.Contains("TW", StringComparison.OrdinalIgnoreCase) || name.Contains("HK", StringComparison.OrdinalIgnoreCase) || name.Contains("MO", StringComparison.OrdinalIgnoreCase) || name.Contains("Hant", StringComparison.OrdinalIgnoreCase) ? "zh-Hant" : "zh-Hans";
        return D.ContainsKey(two) ? two : "en";
    }

    public static void SetLanguage(string? language)
    {
        CurrentLanguage = string.IsNullOrWhiteSpace(language) || language == "auto" ? ResolveSystemLanguage() : D.ContainsKey(language) ? language : "en";
        var cultureName = CurrentLanguage switch { "zh-Hans" => "zh-CN", "zh-Hant" => "zh-TW", _ => CurrentLanguage };
        try
        {
            var culture = CultureInfo.GetCultureInfo(cultureName);
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;
        }
        catch (CultureNotFoundException) { }
    }

    public static string Get(string key)
    {
        if (D.TryGetValue(CurrentLanguage, out var language) && language.TryGetValue(key, out var value)) return value;
        if (D["en"].TryGetValue(key, out var fallback)) return fallback;
        return key;
    }
}