using System.Collections.Generic;
namespace YouTube4KDownloader;
public static class LocalizationManager
{
 private static readonly Dictionary<string,Dictionary<string,string>> D=new()
 {
  ["ko"]=new(){["WindowTitle"]="4K 영상 다운로더",["AppTitle"]="4K 영상 다운로더",["CopyrightNotice"]="본인이 소유하거나 다운로드 허가를 받은 영상에만 사용하세요.",["Language"]="언어",["DownloadTab"]="다운로드",["HistoryTab"]="기록",["VideoUrl"]="영상 URL",["Paste"]="붙여넣기",["AddQueue"]="큐에 추가",["Inspect"]="정보 확인",["InfoPlaceholder"]="영상 정보를 확인하면 제목이 표시됩니다.",["SaveFolder"]="저장 폴더",["Browse"]="찾아보기",["Quality"]="화질",["OutputFormat"]="출력 형식",["Best4K"]="최고 화질 (최대 4K)",["Quality4K"]="4K 2160p",["QualityQHD"]="QHD 1440p",["QualityFHD"]="FHD 1080p",["QualityHD"]="HD 720p",["QualitySD"]="SD 480p",["Playlist"]="재생목록 전체",["Subtitles"]="자막",["AutoSubtitles"]="자동 자막",["Thumbnail"]="썸네일 저장",["Metadata"]="메타데이터 삽입",["OpenAfter"]="완료 후 폴더 열기",["FileName"]="파일명 형식",["BrowserCookies"]="브라우저 로그인",["CookiesFile"]="cookies.txt",["Queue"]="다운로드 큐",["Log"]="로그",["StartQueue"]="큐 다운로드 시작",["Remove"]="선택 제거",["Clear"]="전체 지우기",["Cancel"]="취소",["Title"]="제목",["Status"]="상태",["Progress"]="진행률",["Date"]="날짜",["Format"]="형식",["Success"]="성공",["Redownload"]="다시 다운로드",["ClearHistory"]="기록 지우기",["OpenFolder"]="폴더 열기",["UpdateTools"]="도구 업데이트",["ClearLog"]="로그 지우기",["Waiting"]="대기",["Failed"]="실패",["Ready"]="준비됨",["CheckingInfo"]="정보 확인 중...",["InfoCancelled"]="정보 확인이 취소되었습니다.",["NoTitle"]="제목 없음",["Unknown"]="알 수 없음",["Channel"]="채널",["Duration"]="길이",["PreparingDownload"]="다운로드 준비 중...",["DownloadInProgress"]="다운로드 중",["RemainingTime"]="남은 시간",["Completed"]="완료",["Cancelled"]="취소됨",["QueueComplete"]="다운로드 큐 처리가 완료되었습니다.",["UserCancelled"]="사용자가 다운로드를 취소했습니다.",["UpdatingTools"]="도구 업데이트 중...",["ToolsUpdated"]="yt-dlp와 FFmpeg 업데이트가 완료되었습니다.",["InvalidUrl"]="올바른 영상 URL을 입력해 주세요.",["UrlCheck"]="URL 확인",["ErrorOccurred"]="오류 발생",["ErrorPrefix"]="오류",["ErrorHelp"]="로그를 확인하고 필요하면 도구 업데이트를 실행해 주세요.",["Cancelling"]="취소 중...",["FolderDialogTitle"]="저장 폴더 선택",["CookiesDialogTitle"]="cookies.txt 선택",["CookiesFilter"]="Cookies 파일 (*.txt)|*.txt|모든 파일 (*.*)|*.*",["ToolsReady"]="필수 도구 준비 완료",["DownloadingYtDlp"]="yt-dlp 다운로드 중...",["DownloadingFfmpeg"]="FFmpeg 다운로드 중..."},
  ["en"]=new(){["WindowTitle"]="4K Video Downloader",["AppTitle"]="4K Video Downloader",["CopyrightNotice"]="Use this only for videos you own or have permission to download.",["Language"]="Language",["DownloadTab"]="Download",["HistoryTab"]="History",["VideoUrl"]="Video URL",["Paste"]="Paste",["AddQueue"]="Add to queue",["Inspect"]="Check info",["InfoPlaceholder"]="Video title appears after checking information.",["SaveFolder"]="Save folder",["Browse"]="Browse",["Quality"]="Quality",["OutputFormat"]="Output format",["Best4K"]="Best quality (up to 4K)",["Quality4K"]="4K 2160p",["QualityQHD"]="QHD 1440p",["QualityFHD"]="FHD 1080p",["QualityHD"]="HD 720p",["QualitySD"]="SD 480p",["Playlist"]="Entire playlist",["Subtitles"]="Subtitles",["AutoSubtitles"]="Auto subtitles",["Thumbnail"]="Save thumbnail",["Metadata"]="Embed metadata",["OpenAfter"]="Open folder when complete",["FileName"]="Filename template",["BrowserCookies"]="Browser login",["CookiesFile"]="cookies.txt",["Queue"]="Download queue",["Log"]="Log",["StartQueue"]="Start queue",["Remove"]="Remove selected",["Clear"]="Clear all",["Cancel"]="Cancel",["Title"]="Title",["Status"]="Status",["Progress"]="Progress",["Date"]="Date",["Format"]="Format",["Success"]="Success",["Redownload"]="Download again",["ClearHistory"]="Clear history",["OpenFolder"]="Open folder",["UpdateTools"]="Update tools",["ClearLog"]="Clear log",["Waiting"]="Waiting",["Failed"]="Failed",["Ready"]="Ready",["CheckingInfo"]="Checking information...",["InfoCancelled"]="Information check cancelled.",["NoTitle"]="No title",["Unknown"]="Unknown",["Channel"]="Channel",["Duration"]="Duration",["PreparingDownload"]="Preparing download...",["DownloadInProgress"]="Downloading",["RemainingTime"]="Remaining",["Completed"]="Completed",["Cancelled"]="Cancelled",["QueueComplete"]="Download queue completed.",["UserCancelled"]="Download cancelled by user.",["UpdatingTools"]="Updating tools...",["ToolsUpdated"]="yt-dlp and FFmpeg updated.",["InvalidUrl"]="Enter a valid video URL.",["UrlCheck"]="URL check",["ErrorOccurred"]="An error occurred",["ErrorPrefix"]="Error",["ErrorHelp"]="Check the log and update tools if necessary.",["Cancelling"]="Cancelling...",["FolderDialogTitle"]="Select save folder",["CookiesDialogTitle"]="Select cookies.txt",["CookiesFilter"]="Cookies files (*.txt)|*.txt|All files (*.*)|*.*",["ToolsReady"]="Required tools are ready",["DownloadingYtDlp"]="Downloading yt-dlp...",["DownloadingFfmpeg"]="Downloading FFmpeg..."}
 };
 public static string CurrentLanguage{get;private set;}="ko";
 public static void SetLanguage(string language)=>CurrentLanguage=D.ContainsKey(language)?language:"en";
 public static string Get(string key)=>D.TryGetValue(CurrentLanguage,out var l)&&l.TryGetValue(key,out var v)?v:key;
}
